--[[ 

Author: Otacon 
Modified by: Andyyy

Original github link: https://github.com/Dr-Otacon/esx_holster
Modified version github link: https://github.com/Andyyy7666/Non-ESX-Holster

Support: https://discord.green/andys-development

]]--

Config 				  = {}
Config.cooldown		  = 1700

----------GANG ANIMATION WEAPONS----------
weaponsFull = {
	'WEAPON_KNIFE',
	'WEAPON_HAMMER',
	'WEAPON_BAT',
	'WEAPON_GOLFCLUB',
	'WEAPON_CROWBAR',
	'WEAPON_BOTTLE',
	'WEAPON_DAGGER',
	'WEAPON_HATCHET',
	'WEAPON_MACHETE',
	'WEAPON_BATTLEAXE',
	'WEAPON_POOLCUE',
	'WEAPON_WRENCH',
	'WEAPON_PISTOL',
	'WEAPON_PISTOL50',
	'WEAPON_REVOLVER',
	'WEAPON_SNSPISTOL',
	'WEAPON_HEAVYPISTOL',
	'WEAPON_VINTAGEPISTOL',
	'WEAPON_MACHINEPISTOL',
	'WEAPON_SMOKEGRENADE',
	'WEAPON_BZGAS',
	'WEAPON_MOLOTOV',
	'WEAPON_FLAREGUN',
	'WEAPON_MARKSMANPISTOL',
	'WEAPON_DOUBLEACTION',
	'WEAPON_STONE_HATCHET',
	'WEAPON_KATANAS',
	"WEAPON_APPISTOL",
	"WEAPON_COMBATPISTOL",
	"WEAPON_MINISMG",
	"WEAPON_MICROSMG",
	"WEAPON_PISTOLXM3",
}

-----COP HOLSTER ANIMATION WEAPONS-------
weaponsCop = {
	"WEAPON_PISTOL_MK2",
	"WEAPON_STUNGUN",
	'WEAPON_PAINTBALL',
	"WEAPON_NIGHTSTICK"
}

-----TRUNK WEAPONS-------
weaponsLarge = {
	"WEAPON_ASSAULTRIFLE",
	"WEAPON_PUMPSHOTGUN",
	"WEAPON_ASSAULTSHOTGUN",
	"WEAPON_CARBINERIFLE",
	"WEAPON_SMG",
	"WEAPON_PUMPSHOTGUN_MK2",
	"WEAPON_CARBINERIFLE_MK2",
	"WEAPON_GUSENBERG",
	"WEAPON_MG",
	"WEAPON_ADVANCEDRIFLE",
	"WEAPON_SNIPERRIFLE",
	"WEAPON_COMPACTRIFLE",
	"WEAPON_COMBATPDW",
	"WEAPON_ASSAULTRIFLE_MK2",
	"WEAPON_COMBATMG_MK2",
	"WEAPON_MUSKET",
	"WEAPON_SPECIALCARBINE",
	"WEAPON_SMG_MK2",
	"WEAPON_SPECIALCARBINE_MK2",
	"WEAPON_COMBATPDW",
	"WEAPON_COMPACTRIFLE",
	"WEAPON_ASSAULTSMG",
	"WEAPON_M700",
	"WEAPON_SAWNOFFSHOTGUN",
	"WEAPON_DBSHOTGUN",
	"WEAPON_AUTOSHOTGUN",
	"WEAPON_BULLPUPRIFLE_MK2",
	"WEAPON_BULLPUPSHOTGUN",
	"WEAPON_BEANBAG",
	"WEAPON_HEAVYSHOTGUN",
	"WEAPON_COMBATSHOTGUN",
	"WEAPON_BULLPUPRIFLE",
	"WEAPON_MILITARYRIFLE",
	"WEAPON_HEAVYRIFLE",
	"WEAPON_COMBATMG",
	"WEAPON_HEAVYSNIPER",
	"WEAPON_MARKSMANRIFLE",
	"WEAPON_REMOTESNIPER",
	"WEAPON_HEAVYSNIPER_MK2",
	"WEAPON_MARKSMANRIFLE_MK2",
	-- "WEAPON_GRENADELAUNCHER_SMOKE",
	"WEAPON_TACTICALRIFLE",
	"WEAPON_PRECISIONRIFLE",
}
