-- Use this to block certain vehicle types from spawning without making them blacklisted in qb, this ensures you can still spawn them with /car and use /admincar if say you want to use a certain car for a job vehicle but don't want it driving around e.g. the taco truck form Yellow Jack

-- https://wiki.gtanet.work/index.php?title=Vehicle_Models

Citizen.CreateThread(function()
    while true do
        SetVehicleModelIsSuppressed("taco", true)
		SetVehicleModelIsSuppressed("tourbus", true)
		SetVehicleModelIsSuppressed("frogger", true)
		SetVehicleModelIsSuppressed("swift", true)
		SetVehicleModelIsSuppressed("cuban800", true)
		SetVehicleModelIsSuppressed("stunt", true)
		SetVehicleModelIsSuppressed("buzzard2", true)
		SetVehicleModelIsSuppressed("predator", true)
		SetVehicleModelIsSuppressed("duster", true)
		SetVehicleModelIsSuppressed("lguard", true)
		SetVehicleModelIsSuppressed("dump", true)
		SetVehicleModelIsSuppressed("bulldozer", true)
		SetVehicleModelIsSuppressed("cutter", true)
		SetVehicleModelIsSuppressed("handler", true)
		SetVehicleModelIsSuppressed("mammatus", true)
		SetVehicleModelIsSuppressed("rentalbus", true)
		SetVehicleModelIsSuppressed("docktug", true)
		SetVehicleModelIsSuppressed("longfin", true)
		SetVehicleModelIsSuppressed("toro", true)
		SetVehicleModelIsSuppressed("toro2", true)
		SetVehicleModelIsSuppressed("speeder", true)
		SetVehicleModelIsSuppressed("speeder2", true)
		SetVehicleModelIsSuppressed("seashark", true)
		SetVehicleModelIsSuppressed("seashark2", true)
		SetVehicleModelIsSuppressed("seashark3", true)
		SetVehicleModelIsSuppressed("tropic", true)
		SetVehicleModelIsSuppressed("tropic2", true)
		SetVehicleModelIsSuppressed("suntrap", true)
		SetVehicleModelIsSuppressed("squalo", true)
		SetVehicleModelIsSuppressed("marquis", true)
		SetVehicleModelIsSuppressed("jetmax", true)
		SetVehicleModelIsSuppressed("dinghy", true)
		SetVehicleModelIsSuppressed("dinghy2", true)
		SetVehicleModelIsSuppressed("dinghy3", true)
		SetVehicleModelIsSuppressed("dinghy4", true)
		SetVehicleModelIsSuppressed("rubble", true)
		SetVehicleModelIsSuppressed("mixer", true)
		SetVehicleModelIsSuppressed("mixer2", true)
		SetVehicleModelIsSuppressed("tiptruck", true)
		SetVehicleModelIsSuppressed("tiptruck2", true)
		SetVehicleModelIsSuppressed("flatbed", true)
		Wait(100)
     end
end)